services:
  - type: web
    name: gymai
    env: python
    plan: free
    buildCommand: pip install zipp>=3.19.1 cryptography>=44.0.1 jinja2>=3.1.6 ecdsa>=0.18.0 python-jose[cryptography]>=3.4.0 --upgrade && pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app.main:app --limit-request-line 8190 --limit-request-fields 100 --max-requests 1000 --max-requests-jitter 50 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite+aiosqlite:///gym_ai.db"
      - key: SECRET_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true